mybatis:
  type-aliases-package: com.ssafy.enjoytrip.*.model
  mapper-locations: mapper/**.xml

server:
  port: 80


spring:
  mvc: 
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/static/**



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/enjoytrip?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username : ssafy
    password : ssafy
